### ISSUE TITLE
Service - LogNativeService Bug

### ISSUE THREAD

**Issue by yigitoguz** [yigitoguz/GWP#20]
Bazı property'lerin DB tarafına basılırken hata alınmasını engellenmesi adına servis gözden geçirilmeli

**Comment by yigitoguz** [comment]
Geliştirme yapıldı ve commitlendi, test bekliyor

**Comment by ufuktankiyak** [comment]
Test edildi. AppDomainName yanlış yazıyor.

**Comment by yigitoguz** [comment]
süreç jira üzerinden takip edilecek
