### ISSUE TITLE
AdminUI - ProjectTemplate Page

### ISSUE THREAD

**Issue by ufuktankiyak** [yigitoguz/GWP#30]

**Comment by yigitoguz** [comment]
Sayfa geliştirilmeden önce DB tarafında bazı düzeltmelerin yapılması gerekmekte ve buna baglı olarak development kararları alınacak.Toplantı notları daha sonra eklenecek.

Öncelikle DB tarafında yapılması gereken geliştirmeler;
https://www.evernote.com/shard/s706/sh/2d45a309-2457-4008-b612-ef8df58dcae3/03eabc7bfc4124ffe6ba6f95e5229a0a

**Comment by yigitoguz** [comment]
DB tasarımı elden geçirildi

**Comment by yigitoguz** [comment]
**Notlar**

- ProjectCultureTemplateContent tablosunda HasCategory=true ise Schedule bilgileri null geçilecek

- ProjectCultureTemplateContent tablosunda kanal baglantısı varsa (ContentChannel) HasCategory=false

**Comment by ufuktankiyak** [comment]
**Template Management**

1. Project sayfasından gidilir
2. Açılan sayfada RadioButton ile kategori template mi kanal template mi olduğu sorulur
3. Eğer kategori template seçili ise ProjectCategoryID bilgisi kullanıcıdan istenir
4. ProjectCategoryID bilgisi istenirken kulanıcı kategori ağacı üzerinden seçim yapar

Bu sayfa tasarlanırken recursive yapı kuralları gereği kod yazılır

**Comment by ufuktankiyak** [comment]
**TemplateContent Management**

1. ProjectCultureID DropDownList aracığıyla seçtirilir. DropDown'daki seçilecek itemın formatı Domain(Dil) şeklinde olur
2. Bu sayfaya redirect olurken kanal template bilgisi ile geldiysek ScheduleStartDate ScheduleEndDate alanları sorulur. Kullanıcıya sorulmaksızın IsContentChannel direk true olarak alınır

Bu sayfa tasarlanırken bir önceki sayfadan birden fazla geliş olabileceği için GridView kullanılır

**Comment by yigitoguz** [comment]
Toplantıda alınan son kararlara istinaden yapılan geliştrilmeler buraya eklenmelidir.

**Comment by yigitoguz** [comment]
DB de ProjectCategory ve ProjectTemplateProperty tabloları birleştirilerek Localizasyonel bazlı bazı iyileştirmeler yapılmalıdır ve ardından mevcut sayfa üzerine eklemeler yapılmalıdır

**Comment by ufuktankiyak** [comment]
Tamamlandı
