### ISSUE TITLE
AdminUI -  Category Page 

### ISSUE THREAD

**Issue by yigitoguz** [yigitoguz/GWP#31]

**Comment by yigitoguz** [comment]
DB tarafında LastUpdateDate , CreatedDate , IsDefaultCategory alanlarını kaldıralım.CategoryLabel ismiyla bir alan açalım ve main category'e kaçıncı seviyede baglı oldugunu görelim burdan

Kod tarafında CategoryManagement diye ayrıca bir sayfa olacak.Aynı ProjectManagement gibi (Bu noktadan itibaren masterPage üzerinde tanımlı bir header gerekti sanırım).
Bu sayfa üzerinden proje bagımsız bir şekilde categoryler yönetiliyor olacak.Sayfa üzerine vereceğin linkler yine aynı sayfaya gelecek.

Project Management sayfasına ise bu sayfadan bagımsız olarak Category diye bir hyberlink olacak.Diger sayfadan yönettiğimiz Category dataları bu sayfa üzerinden projeye ile ilişkilendirebiliriz.

Ozetle 2 sayfa yapılacak

**Comment by ufuktankiyak** [comment]
Tamamlandı. Testler yapıldı.

**Comment by yigitoguz** [comment]
Code Refactoring yapıldı
