### ISSUE TITLE
GWPDB - MasterContent table relation to Project table

### ISSUE THREAD

**Issue by yigitoguz** [yigitoguz/GWP#34]
Son alınan kararlar dogrultusunda Content'in baglı oldugu MasterContent tablosu dil bagımsız bir hale gelmiştir.Bu yapıya göre bir Content'in aynı dildeki farklı opsiyonları veya bir Contentin farklı dildeki versiyonlarına hızmet edebilir hale gelmiştir.Bu sebeple MasterContent tablosu ProjectCulture yerine Project tablosuna baglanmalıdır.

**Comment by ufuktankiyak** [comment]
Gerekli işlemler yapıldı
