### ISSUE TITLE
Actual Database Diagrams

### ISSUE THREAD

**Issue by yigitoguz** [yigitoguz/GWP#37]
Database'de yapılan her değişiklik sonrası diagram oluşturularak buraya kopyalanacaktır.

**Comment by yigitoguz** [comment]
**Date: 14.03.2016
Version: Pre-Alpha v0.7**

![asd](https://cloud.githubusercontent.com/assets/13535868/13743833/daa423f4-e9ec-11e5-8af7-62e47a856c4f.png)

**Comment by ufuktankiyak** [comment]
**Date: 14.03.2016
Version: Pre-Alpha v0.8**

![14 03 2016](https://cloud.githubusercontent.com/assets/11792354/13758373/d6e45708-ea31-11e5-8918-f65c7eb30374.png)

**Comment by ufuktankiyak** [comment]
**Date: 23.03.2016
Version: Pre-Alpha v0.9**
![23 03 2016](https://cloud.githubusercontent.com/assets/11792354/14000633/ae2da3bc-f14a-11e5-8a8f-8dba30f7ab41.png)

**Comment by yigitoguz** [comment]
**Date: 01.04.2016
Version: Pre-Alpha v1.0**

![untitled2](https://cloud.githubusercontent.com/assets/13535868/14196625/2657941c-f7cf-11e5-9298-94b0253aadee.png)
