### ISSUE TITLE
AdminUI - ProjectTemplate Page Test

### ISSUE THREAD

**Issue by yigitoguz** [yigitoguz/GWP#39]
Code refactor edildi ve bazı buglar giderildi ve commitlendi.
Bazı senaryolara göre test işlemleri yapılmalıdır. Bunlar;

- Aynı Category için template ekleme
- Aynı Parent Category için template ekleme,
- Aynı Farklı Projeler'deki Category'ler için template ekleme ve tüm bunları yaparken farklı ekranlarda sonuçları karşılaştırma
- Rutin test işlemleri

**Comment by ufuktankiyak** [comment]
Test edildi
