### ISSUE TITLE
AdminUI - ProjectManagement Extra Spec.

### ISSUE THREAD

**Issue by yigitoguz** [yigitoguz/GWP#45]
- Sayfaya data gelmediği durumlarda gridin gözükmesi saglanmalı

- Culture kolonu eklenmeli (Seçilen öge project tablosuna insert edilmeli ancak daha sonradan update edilebilir bir alan olmamalı.Yani dropdown sadece footerda olmalı.DataRow içine label basabiliriz)

**Comment by ufuktankiyak** [comment]
GridView sorunu çözüldü.
ProjectManagement sayfasına DefaultCulture alanı eklendi.
Test edildi.

![image](https://cloud.githubusercontent.com/assets/11792354/14032628/d996fb2a-f21c-11e5-81ac-320203c442ea.png)
