### ISSUE TITLE
AdminUI - ProjectManagement Redirect Pages Info

### ISSUE THREAD

**Issue by ufuktankiyak** [yigitoguz/GWP#46]
- FeatureManagement Page
Project Name info

- CultureManagement
Project Name info

- CategoryManagement
Project Name info,ParentCategory Name
Panel açılıgında hangi kategory'e  insert edileceği panelin hemen üzerinde belirtilmeli

- PropertyManagement
Project Name info

**Comment by yigitoguz** [comment]
süreç jira üzerinden takip edilecek
