### ISSUE TITLE
AdminUI - CategoryManagement Set Property Page

### ISSUE THREAD

**Issue by yigitoguz** [yigitoguz/GWP#53]
Category Management sayfasında istenilen soyut property'ler Category'ye assign edilmelidir.
Checkbox list dynamic olarak create edilmelidir

**Comment by ufuktankiyak** [comment]
1. Kategori sayfasında SetProperty butonuna tıklandığında, grid altında panel açılacak.
2. ProjectProperty öğeleri checkboxlist üzerinde dinamik olmalı.
3. Check olaylarını yakalamalı.
4. Seçilen öğeler CategoryProperty e set edilecek.

**Comment by ufuktankiyak** [comment]
Tamamlandı.
