### ISSUE TITLE
AdminUI - ContentManagement Page

### ISSUE THREAD

**Issue by yigitoguz** [yigitoguz/GWP#54]

**Comment by ufuktankiyak** [comment]
1. AddContent LinkButton'u kategori grid'ine eklenir.
2. Culture dropdownda sorulur.(Lokalize olmuş kategoriler bazında) 
3. Title,imagelar istenir, context kullanıcıya sorulur.
4. Kategorinin propertyleri getirilerek kullanıcıya sorulur ve contentproperty tablosuna insert edilir.
5. Insert ederken mastercontent önce content sonra insert edilir. en son content property insert edilir.
6.Content e opsiyon ekleme ve contenti lokalize etme bu sayfa tamamlandıktan sonra tekrar konusulacak.

**Comment by ufuktankiyak** [comment]
https://www.dropbox.com/s/9opq6t1o5qopb3u/ContentManagement.docx?dl=0

**Comment by yigitoguz** [comment]
sayfa yaratıldı ve ilgili geliştirmeler devam edecek.Bundan sonraki süreci jira üzerinden takip ediyor oalcagız
